apiVersion: v1
kind: Service
metadata:
  name: nodeservice
spec:
  type: NodePort
  selector:
    app: playerdb
  ports:
    - port: 3000 # expose the service on internal port 80
      targetPort: 3000
      nodePort: 30001 #our NodeJS app listens on port 3000
---


# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-18T18:37:49Z"
  name: nodejs-player-app-deployment
  namespace: default
  resourceVersion: "3975"
  selfLink: /api/v1/namespaces/default/services/nodejs-player-app-deployment
  uid: fbd983c9-bdb8-4b25-b1f8-5829c7e53a03
spec:
  clusterIP: 10.99.6.86
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30415
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: playerapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
